### ISSUE TITLE
Provide Url with privacy policy for X2 mobile app

### ISSUE THREAD

**Issue by ppagnone** [chi2labs/website#29]
Google Play is requiring a privacy policy for app.

Currently we are collecting the following:

- name and lastname (for identify user)
- email (for authentication)

The name of application in Google Play is "X2 Mobile (Beta)"

Privacy policy must be available in our website.

**Comment by dietrichson** [comment]
@ppagnone 
Also published here:
https://www.chi2labs.com/privacy_x2mobile.html

**Comment by ppagnone** [comment]
I have updated the last privacy policy to use the available on our website.
